#
# Copyright 2019-2020 Tano Systems
# Copyright 2026 g6094199
#
# Apache-2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Example App
LUCI_DEPENDS:=+luci-base

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=g6094199

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature