name: Build luci-app-tn-vsftpd

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64 # Wir nehmen x86_64 als Referenz-SDK
          FEEDNAME: custom
          PACKAGES: luci-app-tn-vsftpd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-tn-vsftpd-universal
          # Das Sternchen findet die "all.apk" im bin-Ordner
          path: bin/packages/*/custom/*.apk

